<?php

// autoload.php @generated by Composer

// require_once __DIR__ . '/ej12.php';
include 'ej12.php';

$clase = new Algo;

$array = (['s', 'a', 'b', 'e']);

$clase->invertirarray($array);

// return ComposerAutoloaderInit6eebf35a72294610dd6e0ac17fb474ef::getLoader();
?>